language: python
services:
  - postgresql
python:
  - "2.7"
  - "3.3"
  - "3.6"
install: "pip install -r requirements.txt"
script: pytest
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE EXTENSION tablefunc' -d travis_ci_test -U postgres
